[book]
authors = ["joshua-maros"]
language = "en"
multilingual = false
src = "src"
title = "How The Fuck Do Computer Graphics Work?"

[output.html]
additional-css = ["style.css"]
additional-js = ["p5.min.js", "util.js"]
