# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install mdbook
        run: cargo install mdbook
      - name: Build all books
        run: |
          mdbook build computer-graphics
          mkdir to-deploy/
          cp -r computer-graphics/book/ to-deploy/computer-graphics
      - name: Deploy to GH-pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          build_dir: to-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
